language: c++
sudo: required
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "WQ/kLft22FSOLH6ghAS7JB+0CPyFDr4nsY39atUzPOXqYZoNUxLClH6Vb+wI8QdCjW8vdfo4WGclptBcVCVfzuqIpS21Nn1SFOmnDiBBEK9Brol8JTzQg/rFnPg6p0/4s35I7SUVvTFJBZYx2vd24Ap9I8BJeZYBoPvWEJYskB5zaPoYeBfE4lR2NZImQuRriAq4qqvk9eoR7UDbL51V/6N3mM9/DZymY2UnueIFNrteZtBARkaIFl1poAS4pAIysAowIjwZ0j64K7GA10hc7YMEh4LLUqjT2UeW5MR8OOAgVMJ1yxDKejikC9DL0mzYbBHsqbXeABtZ7RhFvdgwtX6vGcfT9DklSXrog1VrpFnLizEGBH7jbHPSjXeBqcE/o28sm/CarKUIfJ0aRBdwaHSPnt/u+dBPXAWZ77+zZKr5SvNPtzSXyt/CUQw/hE2rk16qy44najnqwusJkmxXl8igjpULoTLq5IVzUv+OAbdSX3s4bwPVmfVEf6JE+Nh5Xcqz5tdjFI69KKvmIQkyQlHqiMhl+sImSMnhBQXD/8Qym+oYJojghivbwmzFvNGrgms2/Ut08h4N5s6SQYXcdNFdQDxvqX8nfSuFnNgh/ZxukSoFSqOIuAz9dG3SwU68GKJVGfXH7XEnxB/UcGdVeGio9KyKybZfHpig2wDFrco="
cache:
  directories:
    - /var/cache/apt/
    - /var/cache/pbuilder/aptcache/


matrix:
  include:

   # ###### Ubuntu Linux ####################################################

   # ====== Ubuntu 20.04 (Focal Fossa) ======================================
   - name: "Ubuntu 20.04 (Focal Fossa) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:focal" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 20.04 (Focal Fossa) with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:focal" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 20.04 (Focal Fossa) packaging with pbuilder"
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:focal" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 20.10 (Groovy Gorilla) ======================================
   - name: "Ubuntu 20.10 (Groovy Gorilla) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:groovy" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 20.10 (Groovy Gorilla) with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:groovy" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 20.10 (Groovy Gorilla) packaging with pbuilder"
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:groovy" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 18.04 (Bionic Beaver) ====================================
   - name: "Ubuntu 18.04 (Bionic Beaver) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 18.04 (Bionic Beaver) with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 18.04 (Bionic Beaver) packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 16.04 (Xenial Xerus) =====================================
   - name: "Ubuntu 16.04 (Xenial Xerus) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 16.04 (Xenial Xerus) with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 16.04 (Xenial Xerus) packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 14.04 (Trusty Tahr) ======================================
   - name: "Ubuntu 14.04 (Trusty Tahr) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 14.04 (Trusty Tahr) with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 14.04 (Trusty Tahr) packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" TOOL="pbuilder"


    # ###### Debian Linux ###################################################

    # ====== Debian Testing =================================================
   - name: "Debian Testing with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:testing" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Debian Testing with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:testing" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Testing packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:testing" VARIANT="debian" TOOL="pbuilder"

   # ====== Debian Sid ======================================================
   - name: "Debian Sid with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:sid" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Debian Sid with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:sid" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Sid packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:sid" VARIANT="debian" TOOL="pbuilder"

   # ====== Debian Buster ===================================================
   - name: "Debian Buster with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:buster" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Debian Buster with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:buster" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Buster packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:buster" VARIANT="debian" TOOL="pbuilder"

   # ====== Debian Stretch ==================================================
   - name: "Debian Stretch with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:stretch" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Debian Stretch with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:stretch" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Stretch packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:stretch" VARIANT="debian" TOOL="pbuilder"


   # ###### Fedora Linux ###################################################

   # ====== Fedora 33 =======================================================
   - name: "Fedora 33 with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:33" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Fedora 33 with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:33" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Fedora 33 packaging with mock"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:33" VARIANT="fedora" TOOL="mock"

   # ====== Fedora 32 =======================================================
   - name: "Fedora 32 with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:32" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Fedora 32 with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:32" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Fedora 32 packaging with mock"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:32" VARIANT="fedora" TOOL="mock"

   # ====== Fedora Rawhide ==================================================
   # - name: "Fedora Rawhide with GCC"
   #   os: linux
   #   dist: focal
   #   group: travis_latest
   #   env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   # - name: "Fedora Rawhide with Clang"
   #   os: linux
   #   dist: focal
   #   group: travis_latest
   #   env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   # - name: "Fedora Rawhide packaging with mock"
   #   os: linux
   #   dist: focal
   #   group: travis_latest
   #   env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="mock"


   # ###### FreeBSD #########################################################

   # ====== FreeBSD 12.1-RELEASE ============================================
   - name: "FreeBSD 12.1-RELEASE with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="12.1-RELEASE" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "FreeBSD 12.1-RELEASE with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="12.1-RELEASE" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"

   # ====== FreeBSD 12.2-RELEASE ============================================
   - name: "FreeBSD 12.2-RELEASE with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="12.2-RELEASE" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "FreeBSD 12.2-RELEASE with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="12.2-RELEASE" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"

   # ====== FreeBSD 11.4-RELEASE ============================================
   - name: "FreeBSD 11.4-RELEASE with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="11.4-RELEASE" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "FreeBSD 11.4-RELEASE with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="11.4-RELEASE" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"


   # ###### Other ###########################################################

   # ====== MacOS X =========================================================
   # - name: "MacOS X"
   #   os: osx
   #   osx_image: xcode9.4
   #   compiler: clang
   #   group: travis_latest


   # ###### Special #########################################################

   - name: "Default Build"
     os: linux
     dist: focal
     group: travis_latest
     env: TOOL="compile"

   - name: "Coverity Scan"
     os: linux
     dist: focal
     group: travis_latest
     env:
      - TOOL="coverity"
      - VARIANT="ubuntu"
      - COVERITY_PROJECT="dreibh%2Fsubnetcalc"
      - COVERITY_SCAN_NOTIFICATION_EMAIL="dreibh@simula.no"
      - COVERITY_SCAN_BRANCH="coverity_scan"


before_install:
  - ci/before-install

install:
  - ci/install

script:
  - ci/build
  - ci/test
