# GitHub Actions Scripts
# Copyright (C) 2021-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

name: Fedora Linux CI Tests

on:
  push:
    branches:
      - master
      - main
      - dreibh/github-actions

jobs:

  # #########################################################################
  # #### Build from Sources                                              ####
  # #########################################################################
  Build:

    # ###### Build matrix ###################################################
    strategy:
      matrix:
        include:
          # ====== Fedora Linux =============================================
          - label: "Fedora 43 with Clang"
            image: fedora:43
            cc: clang
            cxx: clang++

    # ###### Build commands #################################################
    name: ${{ matrix.label }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      # NOTE: actions/checkout@v6 does not work for old Ubuntu 18.04!
      - uses: actions/checkout@v6
      - name: Build
        shell: bash
        run: |
          CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ARCH= ci/ci-setup   compile
          CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ARCH= ci/ci-install compile
          CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ARCH= ci/ci-build   compile


  # #########################################################################
  # #### Multi-Architecture Builds                                       ####
  # #########################################################################
  Architectures:
    # ###### Build matrix ###################################################
    strategy:
      matrix:
        include:
          # ====== Fedora Linux =============================================
          - label: "Fedora 43 with Clang/PPC64"
            arch: ppc64le
            distro: fedora43
            cc: clang
            cxx: clang++
          # ====== Fedora Linux =============================================
          - label: "Fedora 43 with Clang/ARMv8"
            arch: aarch64
            distro: fedora43
            cc: clang
            cxx: clang++

    # ###### Build commands #################################################
    name: ${{ matrix.label }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # NOTE: dreibh/run-on-arch-action provides the upstream
      #       uraimo/run-on-arch-action action, with additional dockerfiles
      #       needed for the builds here!
      - uses: dreibh/run-on-arch-action@dreibh/tests
        name: Build
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          run: |
            CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ci/ci-setup   compile
            CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ci/ci-install compile
            CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ci/ci-build   compile


  # #########################################################################
  # #### Build Packages                                                  ####
  # #########################################################################
  Package:
    name: Fedora Packaging
    runs-on: ubuntu-latest
    container:
      # The GitHub runner issue with Mock seems to be fixed now:
      # => https://github.com/rpm-software-management/mock/issues/1487
      image: fedora:43
      options: --privileged --cap-add=SYS_ADMIN
    steps:
      - uses: actions/checkout@v6
      - name: Packaging
        shell: bash
        run: |
          CC=clang CXX=clang++ ARCH= ci/ci-setup   package
          CC=clang CXX=clang++ ARCH= ci/ci-install package
          CC=clang CXX=clang++ ARCH= ci/ci-build   package
          ci/ci-test
